object Libraries {
    //Any Library is added here
    const val ktxCore= "androidx.core:core-ktx:${Versions.core}"
    const val composeui= "androidx.compose.ui:ui:${Versions.compose_version}"
    const val material= "androidx.compose.material:material:${Versions.compose_version}"
    const val tooling_preview= "androidx.compose.ui:ui-tooling-preview:${Versions.compose_version}"
    const val lifecycle_runtime= "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle_runtime}"
    const val activity_compose= "androidx.activity:activity-compose:${Versions.activity_compose}"
    const val lifecycle_compose= "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.lifecycle_viewmodel}"
    const val navigation_compose = "androidx.navigation:navigation-compose:${Versions.lifecycle_navigation}"
    const val flowlayout = "com.google.accompanist:accompanist-flowlayout:${Versions.flowlayout}"
    const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}"
    const val coroutines_core = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    const val viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    const val runtime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle}"
    const val coil = "io.coil-kt:coil-compose:${Versions.coil}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val ksp = "io.github.raamcosta.compose-destinations:animations-core:${Versions.ksp}"
    const val raamcosta = "io.github.raamcosta.compose-destinations:ksp:${Versions.ksp}"
    const val retrofit2 = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val converter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val logging = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp3}"
    const val hilt = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val compiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt_compiler}"
    const val hilt_lifecycle = "androidx.hilt:hilt-lifecycle-viewmodel:${Versions.hilt_viewmodel}"
    const val compiler_hilt = "androidx.hilt:hilt-compiler:${Versions.hilt_}"
    const val nav_compose = "androidx.hilt:hilt-navigation-compose:${Versions.hilt_viewmodel}"
    const val hilt_classpath = "com.google.dagger:hilt-android-gradle-plugin:${Versions.hilt}"
}