object Versions {
    const val name = "1.0"
    const val code = 1
    const val compose_version = "1.0.1"
    const val core = "1.7.0"
    const val activity_compose = "1.7.0"
    const val lifecycle_runtime = "2.4.1"
    const val lifecycle_viewmodel = "1.0.0-alpha07"
    const val lifecycle_navigation = "2.4.0-alpha08"
    const val flowlayout = "0.17.0"
    const val coroutines = "1.5.1"
    const val lifecycle = "2.3.1"
    const val coil = "1.4.0"
    const val timber = "5.0.1"
    const val ksp = "1.3.4-beta"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val okhttp3 = "5.0.0-alpha.2"
    const val hilt = "2.38.1"
    const val hilt_compiler = "2.37"
    const val hilt_viewmodel = "1.0.0-alpha03"
    const val hilt_ = "1.0.0"
    const val kotlin = "1.5.21"
    const val buildToolsVersion = "7.1.3"
}